[profile.default]
src = 'contracts'
out = 'out'
test = 'test-sol'
scripts = "scripts-sol"
libs = [
    'lib',
    'node_modules',
]
remappings = [
    'openzeppelin-solidity/=lib/openzeppelin-contracts/',
    '@openzeppelin/=lib/OpenSum/node_modules/@openzeppelin/',
    'solidity-bytes-utils/=lib/solidity-bytes-utils/',
    'forge-std/=lib/celo-foundry/lib/forge-std/src/',
    'ds-test/=lib/celo-foundry/lib/forge-std/lib/ds-test/src/',
    'celo-foundry/=lib/celo-foundry/src/'
]

no_match_contract = "RandomTest"
verbosity = 3

[profile.integration]

no_match_contract = "RandomTest"
match_contract = "Integration"

[rpc_endpoints]
celo_mainnet="https://forno.celo.org"