apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
{{ include "prometheus.labels" .  | indent 4 }}
  name: prometheus
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}
{{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
{{- end }}
